### ISSUE TITLE
Releases taggées sur Github

### ISSUE THREAD

**Issue by mitsukarenai** [timovn/blogotext#26]
Tout est dans le titre :)  Très pratique pour ne pas rater des mises à jour sur https://github.com/timovn/blogotext/releases.atom

**Comment by BoboTiG** [comment]
Pour la dernière version, Timo, tu peux utiliser ces deux commandes :

    git tag -a 2.1.0.1 -m "Version 2.1.0.1" 6246965
    git push origin --tags

**Comment by timovn** [comment]
Je ne connaissais pas tout ça, merci pour l’info et les commandes !
