### ISSUE TITLE
Recherche par tag avec un seul résultat

### ISSUE THREAD

**Issue by BoboTiG** [timovn/blogotext#30]
Je viens de me rendre compte que lors d'une recherche par tag, s'il n'y a qu'un seul résultat, alors le titre de la page est le titre de l'article. C'est dans [inc/them.php](https://github.com/timovn/blogotext/blob/master/inc/them.php#L226) que ça se passe, voilà [un exemple](http://blog.jmsinfo.co/index.php?tag=Raspberry+Pi).
Étant donné que rien d'autre n'est utilisé dans ce cas, et pour garder la logique de la recherche simple, peut-on envisager de la supprimer ?

**Comment by timovn** [comment]
Supprimer la recherche par tag ? Je préfère la garder.
Normalement, on a le même comportement avec une recherche simple : [exemple](http://lehollandaisvolant.net/index.php?q=Le+num%C3%A9rique+au+coll%C3%A8ge+en+France).

Par contre, s’il n’y a qu’un seul résultat, il faudrait passer sur l’affichage de l’article en entier.

**Comment by BoboTiG** [comment]
Non, non, je me suis mal exprimé. On ne supprime pas la recherche par tag, mais plutôt le comportement. S'il n'y a qu'un seul article trouvé, alors on ne fait rien de spécial, plutôt que de changer le titre de la page comme si l'article en question était affiché.
Si tu souhaites afficher l'article, pour les moteurs de recherche, il y aurait du contenu dupliqué pour deux URL différentes. Pas certain que ça soit correct. Ou alors, en faisant une redirection ?

**Comment by timovn** [comment]
Mh… en effet.
La redirection me semble être une meilleure idée dans ce cas.

L’idée c’est de réduire le nombre de clics : s’il n’y a qu’un article, alors le lecteur va forcément cliquer sur celui-là.

**Comment by BoboTiG** [comment]
Alors la redirection semble une solution correcte :)

**Comment by timovn** [comment]
C’est fait avec commit #d81828d.
