### ISSUE TITLE
Editeur markdown

### ISSUE THREAD

**Issue by kpouget** [timovn/blogotext#33]
Salut,

est-ce que ça t'intéresserait d'intégrer un éditeur Markdown dans blogotext ?
je l'ai dans la version perso, via Pagedown, l'éditeur de Stackoverflow (avec le livepreview).

Pour le moment l'éditeur d'origine et pagedown 'cohabitent', il suffit d'un flag 'md' dans l'URL pour passer de l'un à l'autre (je n'ai pas migré tous mes articles), mais on peut imaginer plutôt une option de configuration.

Si ça t'intéresse, je peux préparer une pull request dans la semaine

Kevin

**Comment by BoboTiG** [comment]
:+1:

**Comment by ccbc** [comment]
Bonjour kpouget,

Je serais hautement intéressé par une version Markdown. L'avez-vous développée?

**Comment by wazari972** [comment]
Bonsoir,

oui, elle est dispo sur https://github.com/wazari972/blogotext mélangée à d'autres customizations.

J'ai vu que Timo avait mis un support simple de markdown, ma version à l'avantage d'être basée sur Pagedown (l'éditeur de stackoverflow), donc avec le live preview et la barre d'outil (dont je ne me sers pas). Je m'en sers sur mes blogs perso donc ça marche très bien, le seul quack qu'il peut y avoir, c'est si d'anciens articles sont écrit avec le support original (dans ce cas, il faut enlever le &md de l'URL pour revenir à l'éditeur par défault)
