### ISSUE TITLE
Utilisation des branches pour les différentes version ?

### ISSUE THREAD

**Issue by foxyantho** [timovn/blogotext#35]
Ne serais-ce pas mieux d'utiliser les branches pour les différentes versions / travaux ?

Exemple :
- master
- develop
- ( pre-release-3 )

Travailler dans `develop`. Pour les pull-requests : forker Blogotext et les balancer aussi dans `develop`. Puis quand tout est ok, de merger le tout sur `master` ?
De cette manière, la branche master sera toujours la plus stable et la plus propre.

```
git checkout master
git merge --no-ff branche-a-merger-dans-master
```

Je ne prétend pas être un pro de Git, mais cela me semble mieux, qu'en pensez-vous ? :smile:

**Comment by BoboTiG** [comment]
:+1:

**Comment by timovn** [comment]
C’est vrai…
Mais je suis encore moins un pro de Git que toi, faut que j’apprenne à faire tout ça, en fait.

Pour le moment, la dernière version stable se trouve sur mon site (lehollandaisvolant.net/blogotext) et ici, c’est purement pour le dév, les erreurs, les demandes de fonctions.

**Comment by FoxyAntho** [comment]
Je ne connais que les fonctions basiques et ça me suffit aussi amplement :smiley: En fait c'est tout bête :

On crée une branche ( synonyme de feature ) :
`git branch mabranche`

Se positionne dedans :
`git checkout mabranche`

Et là, ça fonctionne comme à l'accoutumé en faisant ses petits commits les uns après les autres :smile: 

Une fois que l'on juge le travail bon, stable, on va le merger dans `master` : donc, on se positionne dans `master` avec :
`git checkout master`

Puis on fusionne les changements de `mabranche` avec `master` :
`git merge --no-ff mabranche`
Et c'est fini !

Pourquoi l'option "--no-ff" ? Avis personnel, Git par défaut fait un fast-forward, c'est à dire qu'il met les commits l'un à la suite de l'autre. L'avantage est que l'on peut savoir à quel moment la branche a était crée.
L'autre avantage est que lors du merge il faut dire quoi garder et répéter cette opération ... pour chaque commit de "mabranche" ! Alors qu'avec --no-ff, on doit aussi dire quoi garder, mais uniquement pour les différences entre "master" et "mabranche".

Voici une illustration pour mieux comprendre ce principe : https://i.stack.imgur.com/FMD5h.png

**Comment by timovn** [comment]
Je vais essayer (tardivement) de m’y mettre.

Merci pour toutes les explications et le conseil du "no-ff" (qui me semble une bonne idée aussi).
On verra si ça marche^^
