### ISSUE TITLE
Probème installation Mysql

### ISSUE THREAD

**Issue by ebugnet** [timovn/blogotext#39]
Salut,
Lors d'une installation, au moment du choix Mysql (peut être aussi avec autre chose), les paramètres de la BDD n'apparaissent pas, tu peux donc pas les rentrer.
En effet, la div mysql_vars est en style display:none.

Éric

**Comment by timovn** [comment]
Le changement de formulaire se fait en JavaScript.

Le JS doit être activé dans ton navigateur.
Il est également possible que tu aies une extension de type NoScript d’activée : tu dois la débloquer, au moins pour ton site. Blogotext utilise du JS un peu partout.

**Comment by ebugnet** [comment]
OK, merci, je pensais pourtant tout avoir désactivé mes bloqueurs, en plus dans localhost.
De toute façon j'avais contourné le soucis pour ce qui me concernait.
Éric

**Comment by timovn** [comment]
En fait le problème était bien là. Un autre bug (également à propos de MySQL) vient de me faire voir ça.

Le bug se présentait quand MySQL est présent sur le serveur mais pas SQLite. Tu l’as contourné, le correctif sera publié sous peu.
