### ISSUE TITLE
Undefined var in sqli.php when using MySQL

### ISSUE THREAD

**Issue by CamTosh** [timovn/blogotext#40]
Pendant l'installation je suis tombé sur cette érreur -> 
http://puu.sh/oB3Pi/b7aa5c5e72.png

Je venais de renseigner les id de connexions à la bdd MySQL.

Serveur Apache sous PHP 7.0.3 avec MySQL 5.7.11, rien de spécial dans les modules Apaches ou autre.

Merci de regarder d'où ça vient :)

**Comment by timovn** [comment]
Quelle version de Blogotext : la dernière de github ou celle de mon site ?

**Comment by timovn** [comment]
Bug résolu avec commit d64306a.

Merci de confirmer :p

**Comment by CamTosh** [comment]
Thx ! :)
