### ISSUE TITLE
<p> appears when articles are invisibles

### ISSUE THREAD

**Issue by Artymort** [timovn/blogotext#44]
Hello,

When setting an article to invisible it would seem that the `<p>` stored about the **chapô** starts to appear in the description field of the html header as well as in the edition page of the admin panel (actually, I just checked, for these article it actually appears in the *bt_abstract* of the sql table while it does not for the others). 

Not a major issue and this shouldn't be long to fix, if no one gets to it I'll have a look but someone who knows the structure of the code would do that way faster than I would.

Thanks for the amazing blog engine, I've been using it for a few month and it's amazing!

**EDIT** Ok, sorry, this is not related to the "invisible" article, I just updated from 3.0.1 to 3.3.7 and got confused. The title is now misleading but there is I believe an issue : when you write an article, then edit it, `<p>` start to appears in the **chapô** field *and* in the description field of the html header, and this is not normal.

**Comment by timovn** [comment]
Hi,

How exactly do you reproduce this behavior?

I just did the following:
- went to "new article"
- put something in "title" field, put somthing in "content" field (these fields are required and your browser should not allow you to publish it if these fields are empty)
- set article to "invisible"
- saved it

Nowhere can I find any "<p>", nor in the chapo, the content, the description tag, on public page or on admin side.

When the chapo is empty, nothing is stored in database for that field.

Some "<p>" tag might be stored when you use a very old version of Blogotext (back to 2.x or even the 1.x old text-based blogotext). It might also be the case if you imported some Wordpress XML dump.

**Comment by Artymort** [comment]
Sorry it took a while to reproduce.

I tried on a fresh install of blogotext (3.3.7) under MySQL (and not sqlite) on a freshly installed archlinux lighttpd (1.4.39) and mariadb (10.1.14) server.

To reproduce :

* new article
* non-empty "title", "chapô" and "content"
* no matter whether invisible or not

You have the `<p>` tag stored in the database, hence appearing in various places cited in the first comment.

```mysql
MariaDB [testtest]> SHOW TABLES;
+--------------------+
| Tables_in_testtest |
+--------------------+
| articles           |
| commentaires       |
| links              |
| rss                |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [testtest]> SELECT * FROM articles;
+----+---------+----------------+----------------+----------+-----------------+----------+---------+------------------+-----------------+---------------+-------------+----------------+-------------------+-----------+
| ID | bt_type | bt_id          | bt_date        | bt_title | bt_abstract     | bt_notes | bt_link | bt_content       | bt_wiki_content | bt_categories | bt_keywords | bt_nb_comments | bt_allow_comments | bt_statut |
+----+---------+----------------+----------------+----------+-----------------+----------+---------+------------------+-----------------+---------------+-------------+----------------+-------------------+-----------+
|  6 | article | 20160610165219 | 20160610165219 | Titre    | 
<p>Chapô</p>
  |          |         | 
<p>Contenu</p>
 | Contenu         |               |             |              0 |                 1 |         1 |
+----+---------+----------------+----------------+----------+-----------------+----------+---------+------------------+-----------------+---------------+-------------+----------------+-------------------+-----------+
1 row in set (0.00 sec)
```

Sorry for the poor formatting. (id = 6 as I tried various configurations of invisible/visible articles).
You see the `<p>` tag around the "contenu" which is expected, but also around the "chapô" here.

**Comment by BoboTiG** [comment]
À mon avis, il ne devrait pas avoir les balises "encadrantes" stockées en BDD.

**Comment by timovn** [comment]
@BoboTiG :
For the content, this is normal behavior : I store the date once non-formated (in wiki/markdown syntax) and once as plain HTML, directly usable when the blog is rendered.
This tag is not here in the content on editing.

For the chapo, I don’t know why theses tags are stored (probably something I forgot).

**I reproduced the bug succesfully here**, even with SQLite.
One has only to put something in the "chapo" and it will be put inside P tags.

For the record, I didn’t noticed this bug myself since I let the chapo field empty: a short description is then obtained from the main content.

**Comment by timovn** [comment]
I see why the tag is here : formatting-tags are allowed in the chapo, it has thus to be parsed to HTML, hence the <p> tag, not only around, but everywhere in the chapo if you write multiple lines.

I don’t wish to make the same thing for the chapo as for the content (it’s only a entended to be a small description), So I’ll remove formating possibility for that field.
