### ISSUE TITLE
Erreur drag'n'drop dans  Fichiers 

### ISSUE THREAD

**Issue by Erreur32** [timovn/blogotext#46]
Sur l'onglet Fichiers, la fonction drag'n'drop ne marche pas et impossible de voir les anciens uploads. 

J'ai l'erreur suivante dans les logs apache:

`PHP Fatal error:  Call to undefined function js_drag_n_drop_handle() in /home/www/fichiers.php on line 162, referer: https://blog/fichiers.php?filtre=201606`

J'ai revérifié les droits tout semble ok de ce coté la.

_Merci pour ce super  script  ;)_

**Comment by timovn** [comment]
Bonjour,
Quelle version de Blogotext utilises-tu ?

Il n’y a plus de fonction "js_drag_n_drop_handle" depuis quelques temps.

Quand tu mets à jour Blogotext, il faut remplacer le dossier "inc", mais aussi le dossier "admin" et les fichiers php à la racine (index, rss, atom).

**Comment by Erreur32** [comment]
Bonjour,

effectivement une mauvais UPDATE de ma part...
Désolé pour cette "issue".

Merci à toi.
