### ISSUE TITLE
Probleme d'url pour les rss

### ISSUE THREAD

**Issue by Beanux** [timovn/blogotext#47]
Salut timo,

un truc plutot bête je pense,
les url flux rss générés dans le nuage de tag pour les liens sont (avec le tag bug par exemple):

> rss.php?tag=buglinks

devraient plutot être:

> rss.php?tag=bug&mode=links

J'ai creusé un peu pour voir ou ça se situe, si je me trompe pas ça serait la **ligne 250 de inc/html.php** ? mais pourquoi $mode nest pas set à la ligne 237, je n'en sais trop rien.
Enfin comme je maitrise fortement pas le php, y a toutes les chances que je me trompe, ou que ce soit déjà corrigé.
Le bug est résent sur la version actuelle de ton blog.

ton blogotext va avoir un nouvel utilisateur sous peu ;)
Et continue ainsi !

**Comment by timovn** [comment]
Salut,

Le problème est corrigé, merci pour l’avoir remonté !
C’était bien sur la ligne 250 du fichier html.php : au lien d’afficher `&mode=links` il affichait simplement `links`. Une variable était justement prévue pour ça, d’ailleurs, un peu au dessus : `&ampmode`.

> ton blogotext va avoir un nouvel utilisateur sous peu ;)

Chouette !
N’hésites pas à remonter les problèmes ou à me dire ce qui va pas. Je ne garantis pas de répondre positivement à toutes les demandes de fonctionnalités, mais je suis à l’écoute quand même.
