### ISSUE TITLE
Lire plus tard

### ISSUE THREAD

**Issue by B4rb3rouss** [timovn/blogotext#48]
Une idée pour le lecteur de flux rss. 
Il y a actuellement une icône pour ajouter l'article dans les liens. De la même façon, il serait pratique d'avoir une icône "lire plus tard", qui permettrait de mettre l'article de côté un peu à la façon de wallabag mais en beaucoup plus léger.

**Comment by B4rb3rouss** [comment]
Ravi de lire que c'est en projet.
Merci pour tout timo!

**Comment by timovn** [comment]
Yop !

La fonction est là.
Par contre il faut utiliser un script de migration pour la mise à jour.
Je donne le script ici : https://github.com/timovn/blogotext/commit/808ba1bfe813f0973ff9500320e4a2506290e29d#commitcomment-18369435

C’est basique, mais ça semble marcher.
Tu peux aussi exporter les données, repartir d’une installation fraîche et ré-importer les données.

_NOTE : SAUVEGARDEZ VOS DONNÉES AVANT._

**Comment by B4rb3rouss** [comment]
Merci @timovn .
Je teste ça et rapporte ici les éventuels soucis, s'il y en a :)

**Comment by B4rb3rouss** [comment]
Ça y est, j'ai migré sur la dernière version git, sans soucis particuliers. Je n'ai pas utilisé le script, mais suis parti d'une install fraîche pour être sûr.
Je ne vois cependant pas dans les flux le nouveau bouton "bookmark". Je ne cherche pas où il faut peut-être?

**Comment by timovn** [comment]
Recharges le cache CSS de ton navigateur : le bouton est à droite.
![screenshot at 2016-07-24 14 07 25](https://cloud.githubusercontent.com/assets/4772201/17083685/304041da-51a8-11e6-8566-9a1ad5bc76a1.png)

**Comment by B4rb3rouss** [comment]
Je suis un boulet, c'est dans la branche de dev n'est-ce pas?

**Comment by B4rb3rouss** [comment]
C'était bien ça, sur a branche de dev tout fonctionne bien à première vue :)

**Comment by timovn** [comment]
Oui oui, dans la /dev.
Ça sera mis dans la branche normale, avec d’autres mises à jours, quand ça sera le moment (je ne sais pas quand encore).
