### ISSUE TITLE
Contrainte de violation SQL.

### ISSUE THREAD

**Issue by Pentakonix** [timovn/blogotext#49]
Salut,

Depuis que j'ai restauré je ne peux plus créer de nouveaux articles j'ai ce message d'erreur à chaque fois : 
J'utilise SQLite.

> Erreur ajout article: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: articles.ID

J'ai mis la dernière version de blogotext et même topo.
C'est embêtant, car je n'ai pas trop envie de me coltiner le copier collé de tous mes articles à la main dans une nouvelle installe ... :/

**Comment by timovn** [comment]
Salut,

Tu as _exporté_ les données au format JSON en utilisant quelle version de Blogotext ?
À quel moment as-tu cette erreur : au moment d’importer ? Ou quand tu veux écrire un autre article ?

**Comment by Pentakonix** [comment]
Hello, j'ai le problème lorsque j'essaie de poster un nouvel article.

Quand je dis que j'ai restauré c'est avec ma méthode (en restaurant tout le tar.gz qui contenait mon l'intégralité du repertoire www)

**Comment by timovn** [comment]
Ah, donc tu as fait une sauvegarde manuelle, sans passer par la fonction d’import/export de Blogotext.

Il doit y avoir quelque chose qui a changé pour que ça ne marche plus du jour au lendemain.
Tu as essayé de passer par l’import/export ?
Est-ce que sur une installation toute neuve (sans les anciens articles) tu peux poster plusieurs articles ?
