### ISSUE TITLE
Clean up all files

### ISSUE THREAD

**Issue by BoboTiG** [timovn/blogotext#52]
Do you think it is possible de remove trailing spaces/lines from all files? It will prevent commits with changed lines thant do not concern the commit purpose.

You could use this command to remove trailing spaces:
```shell
    find . \( -name "*.php" -o -name "*.html" -o -name "*.css" -o -name README.md -o -name LICENSE.txt \) -type f -print0 | xargs -0 perl -pi -e 's/ +$//'
```
It will ignore data files.

And to remove trailing lines on each file:
```shell
    find . \( -name "*.php" -o -name "*.html" -o -name "*.css" -o -name README.md -o -name LICENSE.txt \) -type f -print0 | xargs -0 sed -i -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba'
```
Sources:
- [How to remove trailing whitespace of all files recursively?](https://stackoverflow.com/questions/149057/how-to-remove-trailing-whitespace-of-all-files-recursively)
-  [Removing trailing / starting newlines](http://stackoverflow.com/a/7359879/1117028)

**Comment by timovn** [comment]
I ran the first command without noticing any error.
Commit & pushed.
