### ISSUE TITLE
Database stockage

### ISSUE THREAD

**Issue by BoboTiG** [timovn/blogotext#54]
It is more a question than an issue, but still: is it possible to __not__ stock posts formated? Could it be thinkable to have one *raw* storage in database (using BBCodes, like the one we edit) and only format it on display?

For now, if I want to apply changes into inc/*.php files, I have to edit one post to see effects. If formated text was not in DTB, it would be easier for modifications.

**Comment by timovn** [comment]
It was like that before, but it has been changed for performance.

**Comment by BoboTiG** [comment]
Perhaps a new approche using raw data in DTB and a cache system could be a solution? On post edit, the cache is cleared.

**Comment by timovn** [comment]
The actual field in the database is already acting in some way as a cache. It won’t be less painful to view any changes, you'll still have to edit an article to update the cache and see the differences.

For debugging purposes, you can use the `debug($var)` function, that I built in BT (short call for var_dump + die).

**Comment by BoboTiG** [comment]
OK, thank you :)
