### ISSUE TITLE
Le chapô n'apparaît nul part

### ISSUE THREAD

**Issue by WillehKey** [timovn/blogotext#60]
Bonjour,

J'ai fait l'installation très récemment de Blogotext, qui fonctionne très bien, à l'exception du chapô, je l'ai rempli mais j'ai l'impression qu'il ne sert finalement à rien car il ne s'affiche pas sur l'accueil du blog (où l'on voit tous les articles), ni sur l'article une fois ouvert, ni dans le RSS des articles. Il y a une manip à faire en plus ?

Je précise que les fichiers du thème sont bien ceux par défaut, notamment le template/article.html qui affiche {article_contenu} (d'ailleurs ne devrait-il pas plutôt être *chapô ?)

Merci d'avance

**Comment by timovn** [comment]
Le chapo n’est pas utilisé sur le thème actuel, c'est vrai.
Il s’agit en fait d’un petit résumé autrefois utilisé dans le flux RSS, à la places des articles complets et dans certains thèmes.

On peut l’ajouter, mais faut éditer le thème manuellement.
En FTP, copies le dossier "default" du theme en "default_2" (ou n'importe quel autre nom pour toi). Ensuite, dans les préférences de blogotext, sélectionnes ce theme là "default_2" (ou autre chose)
Ensuite, ajoute {article_chapo} quelque part dans le fichier `/template/article.html` dans le dossier de ton thème, qui représente le squelette en HTML des articles.

Le chapo apparaîtra alors sur chaque article.

Perso, je ne le trouve pas très très utile.

**Comment by WillehKey** [comment]
J'avais deja cree un second theme pour le modifier et garder le default, respectivement, j'ai :

/template/article.html :
`{article_chapo} <strong>[...]</strong>`

/template/post.html :
`<strong>{article_chapo}</strong>{article_content}`

Dans ce cas un autre problème survient, c'est qu'il n'y a pas de formatage possible dans le chapo (pas de lien, pas de gras), c'est la seule raison qui fait que je reste le un chapo automatique. Mais je ne comprend pas trop pourquoi ce n'est pas/plus utilisé, je trouve ça plus pratique (une page plus petite, plus navigable pour le blog pour trouver un article, et ne pas avoir tout un article dans l'aggrégateur RSS).

**Comment by timovn** [comment]
Non, pas de formatage. Ça pose des problèmes.
Je pense qu’on devrait faire comme dans Wordpress : faire un système qui tronque le contenu de l’article et qui met un lien « lire la suite » à la fin.
Il y a un système de modules pour le thème public, il sera étoffé à l’avenir, et il sera possible de faire ça.

En attendant, il n’y a pas de moyen de faire ce que tu cherches…

Pour l’antislash `\` qu’il ajoute, c’est un bug connu ( #50  ) . Il a été corrigé dans la version de travail et le sera ensuite dans la version stable.

**Comment by WillehKey** [comment]
D'accord merci, je vais désactiver le chapo pour le moment et regarder comment faire pour ce système plus intéressant.

En prenant la dernière version du GitHub j'aurai donc la version déjà corrigé ?

**Comment by timovn** [comment]
La dernière version de la branche /dev, oui

(par contre la mise à jour est un peu compliquée, il y a une procédure de migration manuelle à appliquer.
Mais si tu exportes les données, réinstalle, puis importe, il ne devrait pas y avoir de soucis.)
