### ISSUE TITLE
"DATE_PREMIER_MESSAGE_BLOG" pas maj après import d’articles plus anciens

### ISSUE THREAD

**Issue by Starsheep08** [timovn/blogotext#61]
Après installation de la version 3.4.7, j'ai essayé d'importer une vieille sauvegarde (de la version 3.3.7) via le fichier json.
Tout fonctionne bien, mis à part que le calendrier dans la sidebar n'affiche aucun article. Comme si les dates n'étaient pas reconnues...
J'ai du coup copier/coller le fichier database.sqlite dans l'espoir de r"soudre le bug, mais ça n'a strictement rien changé.

Une idée pour retrouver les dates ? Merci par avance !

**Comment by timovn** [comment]
Salut,

Le calendrier ne s’affiche pas du tout ?

**Comment by Starsheep08** [comment]
Salut timo,

Alors en fait il ne me propose même pas de revenir vers les mois précédents (là où sont les articles).

Tu peux regarder ça ici : 
http://blog.starsheep.odns.fr/

Et sinon il me semble que j'avais déjà fait la manipulation il y a quelques mois, et cela n'avait pas fonctionné alors que j'avais écrit des articles de test le mois même. Mais c'était ma découverte de blogotext et comme je ne savais pas trop ce que je faisais je n'avais pas signalé le bug...

**Comment by timovn** [comment]
Ah ok.
Le calendrier fonctionne bien, il suffit de regarder sur un mois qui a plusieurs articles, comme Avril : http://starsheep.odns.fr/blog/?d=2016/04

**Première chose** cependant : s’il ne peut pas aller en arrière depuis le mois de juillet, c’est qu’il considère que le mois de juillet est le mois où est apparu le premier article. Il détecte ça à l’installation et ne tient pas compte des imports d’articles plus anciens. Je corrigerai ça.
En attendant, tu peux le changer toi-même en éditant le fichier `/config/config-advanced.ini` et en changeant la ligne:

```
DATE_PREMIER_MESSAGE_BLOG = '201402'
```
Pour toi, tu dois donc renseigner `201604`.
Ceci permet d’éviter au lien "précédent" dans le calendrier de descendre infiniment en arrière. Les moteurs de recherche indéxent tout les liens qu’ils trouvent, et il m’est ainsi déjà arrivé de voir que Google cherche à indexer des articles de l’année 1610 :(.

**Deuxième chose** : s’il affiche le mois de juillet quand tu es sur ton article datant de mai 2016, c’est parce que quand tu es sur un mois avec un seul article, alors il redirige sur cet article directement.
Or vu qu’il ne se considère alors plus en mode "calendrier", il affiche le calendrier du mois en cours, et pas celui de l’article.
Ceci peut-être gênant aussi si on a des mois avec un seul article. Je corrigerai ça aussi.

**Comment by BoboTiG** [comment]
@Timo : le deuxième bug dont tu parles a été fixé avec le commit https://github.com/timovn/blogotext/commit/a8f4bea28f4e6072b5be0f3908173d8133d33bf9 ;)

**Comment by timovn** [comment]
Ah oui, cool alors !

**Comment by BoboTiG** [comment]
Du coup, je rebondis sur ce que tu dis à propos des moteurs de recherche. Est-ce envisageable que le calendrier soit plus "intelligent" ? Je veux dire par là qu'il n'affiche que le mois de l'article précédent/suivant. Comme ça, les premier et dernier articles seront les extrêmes, plus besoin de `DATE_PREMIER_MESSAGE_BLOG` et plus de mois vides.

**Comment by timovn** [comment]
C’est possible, j’avais mis le `DATE_PREMIER_MESSAGE_BLOG` pour réduire le nombre d’accès BDD.
Je vais voir s’il n’est possible de combiner plusieurs requêtes en un : celle pour déterminer le premier article + celles pour déterminer les articles dans un mois.

Si un mois est vide, oui on peur le aller directement au mois ayant un article, c’est une bonne idée.

**Comment by BoboTiG** [comment]
Du coup, quand on écrit un article, l'année pourrait devenir un champ type `number` ? Histoire de pouvoir en faire ce qu'on veut (et ça permettrait de virer la génération des dates se basant sur `DATE_PREMIER_MESSAGE_BLOG`).

**Comment by timovn** [comment]
Le problème des champs `number`, c’est qu’ils virent un éventuel 0 devant : `03` devient `3`. C’est gênant pour les jours et les mois, mais pas pour les années. Ça pourrait marcher.

Aujourd’hui j’aurais pas trop le temps. Je bosse aussi sur l’issue #48 , où je change un peu la structure de la BDD pour réparer des incohérences de conception de jeunesse. Ça demande un peu de code, vu que je ferai une procédure de migration (la MÀJ sera plus bidouillesque…).

**Comment by BoboTiG** [comment]
Ah oui oui, seulement l'année en type `number`.

**Comment by timovn** [comment]
De toute façon, à terme, je crois qu’on pourra remplacer ça par un type `date`. Mais pour le moment ce dernier n’est pas assez supporté (Firefox ne l’implémente pas du tout).

**Comment by Starsheep08** [comment]
Salut !
Merci pour les retours ! En modifiant le `config-advanced.ini` comme indiqué et en intégrant le dernier commit, le calendrier fonctionne à nouveau parfaitement bien. :) Merci encore !
