### ISSUE TITLE
Invalid token issue

### ISSUE THREAD

**Issue by timovn** [timovn/blogotext#69]
The "invalid token error" spawn much too often in Ajax actions (addons, RSS, comments).

Ideas:
We definitely have to keep tokens though, for security reasons, but instead of using a token per query, we could use a token per page. It would be less secure, but what is actually used generates too much errors.

(see comments in pull request #67 )

**Comment by timovn** [comment]
I had a look at two other self-hostable RSS readers and they don’t use tokens.
They use GET requests to mark stuff as read/unread regardless of the session (a "mark as read" link in one session is the same and does work in another session).

I think I’m gonna remove the tokens() for not-really-critical AJAX requests.

**Comment by timovn** [comment]
- Done for RSS with commit 729e02e
- Done for addons with commit afac8f2

I only removed the unique-token for Ajax requests with no-data lose requests.
Actions that results in content being deleted from DB are not impacted are are still using unique tokens.

Besides, the session verification always remains here. If sessions is changed, no actions are executed whatsoever.

**Comment by BoboTiG** [comment]
Great!
