### ISSUE TITLE
printing a page of a blogotext blog does not work

### ISSUE THREAD

**Issue by timovn** [timovn/blogotext#78]
… in Firefox.

- open a blogotext blog
- try to print (even in a pdf file)
- printed stuff is empty or incomplete

Chrome does not seem to have the problem.
There is no @print rule in CSS.

**Comment by remrem** [comment]
I think it's related to #sidenav, go in the firefox dev tools, delete the #sidenav node and try to print (work for me, tested with PDF).

**Comment by timovn** [comment]
does not work properly here. Part of the articles remain cut.
This is no bug in my CSS, it’s a Firefox problem.
