### ISSUE TITLE
Ajouter code d’intégration pour les fichiers audio/vidéo uploadés

### ISSUE THREAD

**Issue by Jagounet** [timovn/blogotext#83]
Bonjour, 

Comment faire pour afficher dans un article, une vidéo que l'on a envoyé via le système de fichier ? 

Elle est en .mp4

**Comment by timovn** [comment]
Effectivement, il faut que j’ajoute le code pour utiliser la balise `video`.

En attendant, les articles prennent en charge le HTML.
Il est donc possible de l’intégrer avec ce code :

```
<video class="media" src="URL_ICI" type="video/webm" load="" controls="controls"></video>
```

En remplaçant `URL_ICI` par l’URL de la vidéo (donnée sur la page du fichier, dans le premier champ des codes d’intégration).

**Comment by Jagounet** [comment]
ok nickel ! MErci

Par contre juste pour info je ne sais pas si c'est normal, lorsque j'envoi un fichier donc, le lien généré n'est pas en httpS, mais juste http alors que tout le reste est en https chez moi. 

Voila, sinon c'est impeccable ce pti blog

**Comment by timovn** [comment]
Le lien produit correspond au lien présent dans la page des préférences. Si le champ « URL du blog » est en HTTPS, le lien produit est en HTTPS aussi.
